apiVersion: v1
kind: ServiceAccount
metadata:
  name: haven-sa
  namespace: haven
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/haven-pod-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: haven-role
  namespace: haven
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: haven-role-binding
  namespace: haven
subjects:
  - kind: ServiceAccount
    name: haven-sa
    namespace: haven
roleRef:
  kind: Role
  name: haven-role
  apiGroup: rbac.authorization.k8s.io
